# Generated by Django 5.2.6 on 2025-09-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('daily_dose_min', models.DecimalField(decimal_places=1, max_digits=10)),
                ('daily_dose_max', models.DecimalField(decimal_places=1, max_digits=10)),
                ('short_desc', models.CharField(max_length=255)),
                ('full_desc', models.TextField()),
                ('img_url', models.URLField()),
            ],
        ),
    ]
