# Generated by Django 5.2.6 on 2025-10-10 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcompositionrequest',
            name='dish',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.dish'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(verbose_name='Пароль'),
        ),
    ]
