# Generated by Django 5.2.6 on 2025-09-24 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название блюда')),
                ('nutrients', models.JSONField(blank=True, default=dict, verbose_name='Пищевая ценность на 100г')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.AlterModelOptions(
            name='nutrient',
            options={'verbose_name': 'Нутриент', 'verbose_name_plural': 'Нутриенты'},
        ),
        migrations.AddField(
            model_name='nutrient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='daily_dose_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, verbose_name='Дневная норма (г/кг массы тела) до'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='daily_dose_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, verbose_name='Дневная норма (г/кг массы тела) от'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='full_desc',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='img_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='short_desc',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.CreateModel(
            name='DishCompositionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('DE', 'Deleted'), ('FO', 'Formed'), ('CO', 'Completed'), ('RE', 'Rejected')], default='DR', max_length=2, verbose_name='Статус')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('formation_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completion_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('body_mass', models.IntegerField()),
                ('dish_mass', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.dish')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Описание блюда',
                'verbose_name_plural': 'Описания блюд',
            },
        ),
        migrations.CreateModel(
            name='DishCompositionNutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_dish', models.DecimalField(blank=True, decimal_places=1, max_digits=10, verbose_name='Количество в блюде')),
                ('daily_dose_percentage', models.IntegerField(max_length=10, verbose_name='Доля в дневной норме')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.nutrient', verbose_name='Нутриент')),
                ('dish_composition_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.dishcompositionrequest', verbose_name='Запрос на описание')),
            ],
            options={
                'verbose_name': 'Список нутриентов в запросе на описание',
                'verbose_name_plural': 'Списки нутриентов в запросах на описание',
                'unique_together': {('dish_composition_request', 'nutrient')},
            },
        ),
    ]
