# Generated by Django 5.2.6 on 2025-09-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dish_alter_nutrient_options_nutrient_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcompositionnutrients',
            name='daily_dose_percentage',
            field=models.IntegerField(blank=True, verbose_name='Доля в дневной норме'),
        ),
    ]
