# Generated by Django 5.2.6 on 2025-09-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_dishcompositionnutrients_daily_dose_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcompositionnutrients',
            name='daily_dose_percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Доля в дневной норме'),
        ),
        migrations.AlterField(
            model_name='dishcompositionnutrients',
            name='quantity_in_dish',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Количество в блюде'),
        ),
    ]
