# Generated by Django 5.2.6 on 2025-09-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_dishcompositionnutrients_daily_dose_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcompositionrequest',
            name='nutrients',
            field=models.ManyToManyField(related_name='dish_compositions', through='main.DishCompositionNutrients', to='main.nutrient'),
        ),
    ]
