# Generated by Django 5.2.6 on 2025-09-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dishcompositionrequest_nutrients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishcompositionrequest',
            name='nutrients',
        ),
    ]
