# Generated by Django 5.2.6 on 2025-09-26 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_dishcompositionrequest_nutrients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcompositionrequest',
            name='body_mass',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dishcompositionrequest',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.dish'),
        ),
        migrations.AlterField(
            model_name='dishcompositionrequest',
            name='dish_mass',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
