# Generated by Django 5.2.6 on 2025-09-26 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_dishcompositionrequest_body_mass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcompositionrequest',
            name='body_mass',
            field=models.IntegerField(blank=True, default=70),
        ),
        migrations.AlterField(
            model_name='dishcompositionrequest',
            name='dish',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.dish'),
        ),
        migrations.AlterField(
            model_name='dishcompositionrequest',
            name='dish_mass',
            field=models.IntegerField(blank=True, default=500),
        ),
    ]
