# Generated by Django 5.2.6 on 2025-10-01 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_dishcompositionrequest_body_mass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcompositionnutrients',
            name='daily_dose_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Доля в дневной норме'),
        ),
        migrations.AlterField(
            model_name='dishcompositionrequest',
            name='body_mass',
            field=models.IntegerField(blank=True, default=70, null=True),
        ),
        migrations.AlterField(
            model_name='dishcompositionrequest',
            name='dish',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.dish'),
        ),
        migrations.AlterField(
            model_name='dishcompositionrequest',
            name='dish_mass',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
    ]
