# Generated by Django 5.2.6 on 2025-09-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_dishcompositionrequest_body_mass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='daily_dose_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Дневная норма (г/кг массы тела) до'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='daily_dose_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Дневная норма (г/кг массы тела) от'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='full_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='short_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание'),
        ),
    ]
